version: "3.8"
services:
  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: always
    # do not expose ports unless you explicitly need to connect to the mqtt
    # server from the outside of the docker compose network 
    # ports:
    #   - 1883:1883
    #   - 9001:9001
    volumes:
      - ./data/mqtt:/mosquitto/config
  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    restart: always
    volumes:
      - ./data/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Berlin
    devices:
      - /dev/ttyUSB0:/dev/ttyACM0
  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant   
    restart: always
    ports:
      - "8123:8123"
    volumes:
      - ./data/home-assistant:/config
      - "/etc/localtime:/etc/localtime:ro"
